services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///flower_shop.db
      - SECRET_KEY=dev-secret-key
      - RAILWAY_ENVIRONMENT=development
    volumes:
      # Hot reload для разработки
      - ./backend/app:/app/backend/app:ro
      - ./src:/app/src:ro
      # Mount SQLite database
      - ./backend/flower_shop.db:/app/backend/flower_shop.db
    command: >
      sh -c "cd backend && 
             uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"