services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flower_shop
      - SECRET_KEY=dev-secret-key
      - RAILWAY_ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Hot reload для разработки
      - ./backend/app:/app/backend/app:ro
      - ./src:/app/src:ro
    command: >
      sh -c "cd backend && 
             alembic upgrade head &&
             python init_test_data.py || true &&
             uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flower_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: