[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables (will be merged with Railway dashboard vars)
[variables]
INIT_DATA = "false"  # Set to "true" to initialize test data on first deploy