"""add_permissions_to_users

Revision ID: 0fad4fe9421a
Revises: a95a598425e6
Create Date: 2025-08-05 15:46:56.059376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fad4fe9421a'
down_revision: Union[str, None] = 'a95a598425e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    
    # Set default permissions for existing users based on their role
    from sqlalchemy import text
    conn = op.get_bind()
    
    # Admin gets all permissions
    conn.execute(text("""
        UPDATE users 
        SET permissions = '{"orders": true, "warehouse": true, "customers": true, "production": true, "settings": true, "users": true}'
        WHERE role = 'admin'
    """))
    
    # Manager gets most permissions except users
    conn.execute(text("""
        UPDATE users 
        SET permissions = '{"orders": true, "warehouse": true, "customers": true, "production": true, "settings": true, "users": false}'
        WHERE role = 'manager'
    """))
    
    # Florist gets orders and production
    conn.execute(text("""
        UPDATE users 
        SET permissions = '{"orders": true, "warehouse": false, "customers": false, "production": true, "settings": false, "users": false}'
        WHERE role = 'florist'
    """))
    
    # Courier gets only orders
    conn.execute(text("""
        UPDATE users 
        SET permissions = '{"orders": true, "warehouse": false, "customers": false, "production": false, "settings": false, "users": false}'
        WHERE role = 'courier'
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
