"""Merge Delivery model into Supply and link WarehouseItem

Revision ID: 50489c800785
Revises: 9e14c68966fa
Create Date: 2025-07-31 11:55:48.358910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50489c800785'
down_revision: Union[str, None] = '9e14c68966fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add nullable columns first
    op.add_column('supplies', sa.Column('farm', sa.String(), nullable=True))
    op.add_column('supplies', sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('supplies', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('supplies', sa.Column('rate', sa.Float(), nullable=True))
    op.add_column('supplies', sa.Column('comment', sa.String(), nullable=True))
    
    # Update existing records to have default values
    op.execute("UPDATE supplies SET delivery_date = created_at WHERE delivery_date IS NULL")
    op.execute("UPDATE supplies SET currency = 'KZT' WHERE currency IS NULL")
    op.execute("UPDATE supplies SET rate = 1.0 WHERE rate IS NULL")
    op.execute("UPDATE supplies SET supplier = 'Unknown' WHERE supplier IS NULL OR supplier = ''")
    
    # Now make the columns non-nullable after setting values
    op.alter_column('supplies', 'delivery_date',
               existing_type=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('supplies', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('supplies', 'rate',
               existing_type=sa.Float(),
               nullable=False)
    op.alter_column('supplies', 'supplier',
               existing_type=sa.VARCHAR(),
               nullable=False)
               
    op.add_column('supply_items', sa.Column('batch_code', sa.String(), nullable=True))
    op.add_column('warehouse_items', sa.Column('supply_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouse_items', 'supply_items', ['supply_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_items', type_='foreignkey')
    op.drop_column('warehouse_items', 'supply_item_id')
    op.drop_column('supply_items', 'batch_code')
    op.alter_column('supplies', 'supplier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('supplies', 'comment')
    op.drop_column('supplies', 'rate')
    op.drop_column('supplies', 'currency')
    op.drop_column('supplies', 'delivery_date')
    op.drop_column('supplies', 'farm')
    # ### end Alembic commands ###
