"""Add storefront fields to Order model

Revision ID: 6b71a0adc61a
Revises: e51aeee7b61c
Create Date: 2025-08-04 14:32:05.372850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b71a0adc61a'
down_revision: Union[str, None] = 'e51aeee7b61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('card_text', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_time_text', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'source')
    op.drop_column('orders', 'delivery_time_text')
    op.drop_column('orders', 'card_text')
    # ### end Alembic commands ###
