"""Add decorative materials and calculator settings tables

Revision ID: 7238f6ffce7d
Revises: daf1f17ffd0d
Create Date: 2025-08-04 18:06:19.454799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7238f6ffce7d'
down_revision: Union[str, None] = 'daf1f17ffd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculator_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('default_labor_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommended_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('premium_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id')
    )
    op.create_index(op.f('ix_calculator_settings_id'), 'calculator_settings', ['id'], unique=False)
    op.create_table('decorative_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decorative_materials_id'), 'decorative_materials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decorative_materials_id'), table_name='decorative_materials')
    op.drop_table('decorative_materials')
    op.drop_index(op.f('ix_calculator_settings_id'), table_name='calculator_settings')
    op.drop_table('calculator_settings')
    # ### end Alembic commands ###
