"""Add order photos table and extend comments model

Revision ID: a95a598425e6
Revises: 31c8a9ba744e
Create Date: 2025-08-04 19:38:42.168807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95a598425e6'
down_revision: Union[str, None] = '31c8a9ba744e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create order_photos table first
    op.create_table('order_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('photo_type', sa.Enum('pre_delivery', 'completion', 'process', name='phototype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('customer_feedback', sa.Enum('like', 'dislike', name='customerfeedback'), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('feedback_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_photos_id'), 'order_photos', ['id'], unique=False)
    op.create_index(op.f('ix_order_photos_order_id'), 'order_photos', ['order_id'], unique=False)
    
    # Add new columns to comments table with default values
    op.add_column('comments', sa.Column('author_type', sa.Enum('staff', 'customer', name='authortype'), nullable=False, server_default='staff'))
    op.add_column('comments', sa.Column('customer_name', sa.String(), nullable=True))
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'customer_name')
    op.drop_column('comments', 'author_type')
    
    # Drop order_photos table
    op.drop_index(op.f('ix_order_photos_order_id'), table_name='order_photos')
    op.drop_index(op.f('ix_order_photos_id'), table_name='order_photos')
    op.drop_table('order_photos')
    # ### end Alembic commands ###
