"""Add supply_item_id to warehouse_items and product_ingredients table

Revision ID: c3faca8869d2
Revises: ff770d44ed65
Create Date: 2025-07-31 13:54:34.948263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3faca8869d2'
down_revision: Union[str, None] = 'ff770d44ed65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('delivery_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('supplies', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('supplies', sa.Column('rate', sa.Float(), nullable=False))
    op.add_column('supplies', sa.Column('comment', sa.String(), nullable=True))
    op.alter_column('supplies', 'supplier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('supply_items', sa.Column('batch_code', sa.String(), nullable=True))
    op.create_foreign_key(None, 'warehouse_items', 'supply_items', ['supply_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_items', type_='foreignkey')
    op.drop_column('supply_items', 'batch_code')
    op.alter_column('supplies', 'supplier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('supplies', 'comment')
    op.drop_column('supplies', 'rate')
    op.drop_column('supplies', 'currency')
    op.drop_column('supplies', 'delivery_date')
    # ### end Alembic commands ###
