"""Add storefront fields to Shop model

Revision ID: e51aeee7b61c
Revises: 2141049ca290
Create Date: 2025-08-04 14:10:56.085106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51aeee7b61c'
down_revision: Union[str, None] = '2141049ca290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
    op.add_column('shops', sa.Column('shop_domain', sa.String(length=50), nullable=True))
    op.add_column('shops', sa.Column('shop_logo_url', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_shops_shop_domain'), 'shops', ['shop_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_shop_domain'), table_name='shops')
    op.drop_column('shops', 'shop_logo_url')
    op.drop_column('shops', 'shop_domain')
    op.drop_column('shops', 'whatsapp_number')
    # ### end Alembic commands ###
